version: '3'

services:
  app:
    build: ./
    image: dbc
    ports:
      - "4040:4040"
    environment:
      NODE_ENV: production
      SERVER_PORT: 4040
      JWT_SECRET: 0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      MONGO_HOST: mongodb://mongo/dbc
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
    restart: on-failure
    ports:
      - "27017:27017"
